### ISSUE TITLE
画像のトリミング

### ISSUE THREAD

**Issue by Great-grape-channel** [shiosyakeyakini-info/miria#167]
0.0.9+48で画像のトリミングをしても同じ大きさで中心になります
![Screenshot_20230714-075206](https://github.com/shiosyakeyakini-info/miria/assets/87528269/dc2040a2-88f1-4a7a-afa8-4e33cf82a036)
![Screenshot_20230714-075226](https://github.com/shiosyakeyakini-info/miria/assets/87528269/40c3d889-6f60-45a1-82a8-60782ffe5464)
![Screenshot_20230714-075217](https://github.com/shiosyakeyakini-info/miria/assets/87528269/0b4b4e25-1aa5-421f-b7e9-abeade7893f0)

**Comment by poppingmoon** [comment]
x軸またはy軸のどちらかの大きさを固定したときに再現しました

**Comment by shiosyakeyakini-info** [comment]
なんでだろ 再現しない……

**Comment by shiosyakeyakini-info** [comment]
来週こそAndroidの中古の実機を買うのでそれから調査しよ
（iPhone SE 第3世代だと何回かやっても再現しなかった）

**Comment by poppingmoon** [comment]
y方向のみ動かしたときに_drawImageで次のエラーが出ました
多分クロップサイズが元の画像を超えていた時の処理がプラットフォームによって違うのだと思います

```
E/flutter ( 8619): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
E/flutter ( 8619): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:874)
E/flutter ( 8619): 	at com.fluttercandies.image_editor.core.ImageHandler.handleClip(ImageHandler.kt:95)
E/flutter ( 8619): 	at com.fluttercandies.image_editor.core.ImageHandler.handle(ImageHandler.kt:22)
E/flutter ( 8619): 	at com.fluttercandies.image_editor.ImageEditorPlugin.handle(ImageEditorPlugin.kt:217)
E/flutter ( 8619): 	at com.fluttercandies.image_editor.ImageEditorPlugin.access$handle(ImageEditorPlugin.kt:28)
E/flutter ( 8619): 	at com.fluttercandies.image_editor.ImageEditorPlugin$onMethodCall$$inlined$runOnBackground$1.run(ImageEditorPlugin.kt:228)
E/flutter ( 8619): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/flutter ( 8619): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/flutter ( 8619): 	at java.lang.Thread.run(Thread.java:1012)
E/flutter ( 8619): , , null, null)
E/flutter ( 8619): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 8619): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 8619): <asynchronous suspension>
E/flutter ( 8619): #2      NativeChannel.memoryToMemory (package:image_editor_platform_interface/src/channel.dart:50:20)
E/flutter ( 8619): <asynchronous suspension>
E/flutter ( 8619): #3      ImageEditorCommon.editImage (package:image_editor_common/image_editor_common.dart:32:13)
E/flutter ( 8619): <asynchronous suspension>
E/flutter ( 8619): #4      PhotoEditStateNotifier._drawImage (package:miria/state_notifier/photo_edit_page/photo_edit_state_notifier.dart:118:20)
E/flutter ( 8619): <asynchronous suspension>
E/flutter ( 8619): #5      PhotoEditStateNotifier.draw (package:miria/state_notifier/photo_edit_page/photo_edit_state_notifier.dart:127:25)
E/flutter ( 8619): <asynchronous suspension>
E/flutter ( 8619): 
```

**Comment by poppingmoon** [comment]
ここでoffsetを先にvalidateしてvalidatedOffsetを使ってvalidatedCropSizeを作ればよさそう

https://github.com/shiosyakeyakini-info/miria/blob/0112e9923d9f2b6969958f5d12904ce123139651/lib/state_notifier/photo_edit_page/photo_edit_state_notifier.dart#L200-L204

**Comment by poppingmoon** [comment]
ここで +1 しているのはなぜですか？

https://github.com/shiosyakeyakini-info/miria/blob/0112e9923d9f2b6969958f5d12904ce123139651/lib/state_notifier/photo_edit_page/photo_edit_state_notifier.dart#L201-L202

**Comment by shiosyakeyakini-info** [comment]
widthとheightを少なくとも1px以上確保するためにそうしたような気がします

**Comment by shiosyakeyakini-info** [comment]
（いま見直すとそれならmax(1, ... ）でいいやってなってる）
