### ISSUE TITLE
MiAuthで初回ログイン時に許可を与えずに「認証してきた」を押すとインジケーターが消えない

### ISSUE THREAD

**Issue by poppingmoon** [shiosyakeyakini-info/miria#197]
validateMiAuth でエラーが発生すると expectFailure によってダイアログが表示されるがエラーはキャッチされて処理が続行する

https://github.com/shiosyakeyakini-info/miria/blob/c255efb4cbe22a7c20e0a925a38f8182ebe79e82/lib/view/login_page/mi_auth_login.dart#L84-L87

初回ログイン時は tabSettings が空なので以下でエラーが発生する

https://github.com/shiosyakeyakini-info/miria/blob/c255efb4cbe22a7c20e0a925a38f8182ebe79e82/lib/view/login_page/mi_auth_login.dart#L89-L93

```
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      MiAuthLoginState.build.<anonymous closure> (package:miria/view/login_page/mi_auth_login.dart:93:32)
<asynchronous suspension>
```

これがキャッチされ finally に跳ぶが、`IndicatorView.hideIndicator(context)` は `Navigator.of(context).pop()` でしかないので expectFailure のダイアログがpopされる

https://github.com/shiosyakeyakini-info/miria/blob/c255efb4cbe22a7c20e0a925a38f8182ebe79e82/lib/view/login_page/mi_auth_login.dart#L97

そのためダイアログは表示されず、インジケーターは消えない

**Comment by poppingmoon** [comment]
expectFailureをやめて、catchでインジケーターを閉じてダイアログを出せばいいんじゃないかと思います
