### ISSUE TITLE
[beta] アカウント設定でのフリーズ

### ISSUE THREAD

**Issue by ruruke** [shiosyakeyakini-info/miria#638]
## 再現方法

動作情報
OS: ios-18.0.1
Miria: 2.0.0+110

1. アカウント設定からアカウントを削除
2. アカウント設定からアカウントを登録
3. ホーム画面に遷移後アカウント設定を開き「アカウント設定を終わる」ボタンを押す

## 動画
https://youtube.com/shorts/ygnNQU_vQlk

## 画像
![IMG_1597-1729813950995](https://github.com/user-attachments/assets/588e0bd8-d3c0-43d0-8d36-9c29d2054de5)

## 最後に
初めてのissueなので色々不手際があると思いますが……何卒よろしくお願いいたします。

**Comment by 4ster1sk** [comment]
![image](https://github.com/user-attachments/assets/dfdc5814-a930-4b43-adc7-028cd9eb4b94)
何度かやってみたらエラーログ出せた

**Comment by 4ster1sk** [comment]
エラーでないときもあるな…

**Comment by 4ster1sk** [comment]
![image](https://github.com/user-attachments/assets/6bd07832-9075-4920-87f3-bc7080a03203)
WidgetTreeみたらなにもなかった…。えぇ…？

**Comment by 4ster1sk** [comment]
```
ElevatedButton(
                onPressed: () async {
                  context.router.removeWhere((route) => true);
                  await Future.delayed(const Duration(seconds: 1));
                  await context.router.push(const SplashRoute());
                },
                child: Text(S.of(context).quitAccountSettings),
```
Future.delayed(const Duration(seconds: 1));を入れてみたところ同様の状態が確実に再現できるように

**Comment by shiosyakeyakini-info** [comment]
単にアカウント削除→アカウント設定を終わる　だけで再現するっぽい？
```

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#1      ProviderElementBase.watch (package:riverpod/src/framework/element.dart:710:18)
#2      account (package:miria/providers.dart:103:51)
#3      new AccountProvider.<anonymous closure> (package:miria/providers.g.dart:850:20)
#4      ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41:15)
#5      _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:390:12)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#8      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#9      BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
#19     ListBase.firstWhere (dart:collection/list.dart:132:5)
#20     account.<anonymous closure> (package:miria/providers.dart:105:32)
#21     ProviderElementBase.watch (package:riverpod/src/framework/element.dart:703:19)
#22     account (package:miria/providers.dart:103:51)
#23     new AccountProvider.<anonymous closure> (package:miria/providers.g.dart:850:20)
#24     ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41:15)
#25     _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:390:12)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#28     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#29     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#36     _invoke (dart:ui/hooks.dart:312:13)
#37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#38     _drawFrame (dart:ui/hooks.dart:283:31)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#1      ProviderElementBase.watch (package:riverpod/src/framework/element.dart:710:18)
#2      account (package:miria/providers.dart:103:51)
#3      new AccountProvider.<anonymous closure> (package:miria/providers.g.dart:850:20)
#4      ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41:15)
#5      _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:390:12)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#8      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#9      BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
#19     ListBase.firstWhere (dart:collection/list.dart:132:5)
#20     account.<anonymous closure> (package:miria/providers.dart:105:32)
#21     ProviderElementBase.watch (package:riverpod/src/framework/element.dart:703:19)
#22     account (package:miria/providers.dart:103:51)
#23     new AccountProvider.<anonymous closure> (package:miria/providers.g.dart:850:20)
#24     ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41:15)
#25     _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:390:12)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#28     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#29     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#36     _invoke (dart:ui/hooks.dart:312:13)
#37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#38     _drawFrame (dart:ui/hooks.dart:283:31)

```

**Comment by shiosyakeyakini-info** [comment]
```dart
          Align(
            alignment: Alignment.center,
            child: Padding(
              padding: const EdgeInsets.all(10),
              child: ElevatedButton(
                onPressed: () async {
                  final newState = ref.refresh(accountsProvider);
                  print(newState);
                  context.router.removeWhere((route) => true);
                  await context.router.push(const SplashRoute());
                },
                child: Text(S.of(context).quitAccountSettings),
              ),
            ),
          ),
```
にしたらなんか謎な動きになった

**Comment by shiosyakeyakini-info** [comment]
```dart
Align(
            alignment: Alignment.center,
            child: Padding(
              padding: const EdgeInsets.all(10),
              child: ElevatedButton(
                onPressed: () async {
                  final newState = ref.refresh(accountsProvider);
                  print(newState);
                  final router = context.router..removeWhere((route) => true);
                  await Future.delayed(const Duration(seconds: 1));
                  await router.push(const SplashRoute());
                },
                child: Text(S.of(context).quitAccountSettings),
              ),
            ),
          ),
```
にしたら治った？？？？？

**Comment by shiosyakeyakini-info** [comment]
謎

**Comment by shiosyakeyakini-info** [comment]
`await Future.delayed(const Duration(seconds: 1));`じゃなくて`WidgetsBinding.instance.addPostFrameCallback`でもよさそう

**Comment by 4ster1sk** [comment]
`lib/repository/import_export_repository.dart`と`lib/view/settings_page/tab_settings_page/tab_settings_list_page.dart`でも起きそう…？

**Comment by poppingmoon** [comment]
ナビゲーターのスタックが空になっているのが原因だと思います
ここでの意図はボタンを押したときに履歴を消してSplashPageを開くことなので単純に 

```dart
onPressed: () async {
  await context.router.replaceAll([const SplashRoute()]);
},
```

のようにすればよさそうです

**Comment by 4ster1sk** [comment]
なるほど、たしかにその方法のほうがよさそうー
ありがとうございます

**Comment by 4ster1sk** [comment]
うーん、変えてみたら起きるようになってしまった…。

**Comment by poppingmoon** [comment]
https://stackoverflow.com/a/73784156 の方法を使ったら起きなくなったかも

```dart
await context.router.pushAndPopUntil(
  const SplashRoute(),
  predicate: (_) => false,
);
```

再現方法

1. APIキーでアカウントを追加する
2. タブ設定の反映するボタンを押す

**Comment by 4ster1sk** [comment]
良さそう🙏
