### ISSUE TITLE
「ブラウザで開く」から戻ってくるとアプリが落ちる

### ISSUE THREAD

**Issue by yuxxxx** [shiosyakeyakini-info/miria#92]
いくつかのノートで確認してみましたが、今のところ確実に落ちます。

# 再現手順

1. タイムラインから任意のノートの「…」を押す
2. 「ブラウザで開く」を押す
3. 戻る
4. **アプリが落ちる**

# 発生環境

端末: Pixel6
OS: Android 13
Miria: 0.0.6+19
Chrome: 113.0.5672.162
Misskey: 13.12.2(misskey.io)

**Comment by yuxxxx** [comment]
iPhone 14 Proで確認しましたがこちらは落ちませんでした。
他の端末が手元にないのでこれ以上調べられませんが、Androidのみで起きるようです。

**Comment by poppingmoon** [comment]
Pixel 5a (Android 13) で再現しました

**Comment by poppingmoon** [comment]
`flutter pub upgrade` したら起こらなくなりました
url_launcherの問題だったようです

https://stackoverflow.com/questions/76244218/flutter-url-launcher-plugin-throws-java-lang-illegalargumentexception-receiver

**Comment by shiosyakeyakini-info** [comment]
Android 13のエミュレータでも再現
```
D/AndroidRuntime( 8471): Shutting down VM
E/AndroidRuntime( 8471): FATAL EXCEPTION: main
E/AndroidRuntime( 8471): Process: info.shiosyakeyakini.miria, PID: 8471
E/AndroidRuntime( 8471): java.lang.RuntimeException: Unable to destroy activity {info.shiosyakeyakini.miria/io.flutter.plugins.urllauncher.WebViewActivity}: java.lang.IllegalArgumentException: Receiver not registered: io.flutter.plugins.urllauncher.WebViewActivity$1@1a1f95f
E/AndroidRuntime( 8471): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5409)
E/AndroidRuntime( 8471): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5442)
E/AndroidRuntime( 8471): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
E/AndroidRuntime( 8471): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 8471): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime( 8471): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime( 8471): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime( 8471): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8471): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8471): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8471): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 8471): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 8471): Caused by: java.lang.IllegalArgumentException: Receiver not registered: io.flutter.plugins.urllauncher.WebViewActivity$1@1a1f95f
E/AndroidRuntime( 8471): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
E/AndroidRuntime( 8471): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1836)
E/AndroidRuntime( 8471): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
E/AndroidRuntime( 8471): 	at io.flutter.plugins.urllauncher.WebViewActivity.onDestroy(WebViewActivity.java:170)
E/AndroidRuntime( 8471): 	at android.app.Activity.performDestroy(Activity.java:8562)
E/AndroidRuntime( 8471): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1452)
E/AndroidRuntime( 8471): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5396)
E/AndroidRuntime( 8471): 	... 13 more
I/Process ( 8471): Sending signal. PID: 8471 SIG: 9
Lost connection to device.

```

**Comment by shiosyakeyakini-info** [comment]
わ　ほんとに ``url_launcher_android 6.0.35 (was 6.0.33)``でなおった
0.0.7+21 でなおると思います

**Comment by shiosyakeyakini-info** [comment]
直したのをリリースしたのでとじておきます
